[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = [
  "cd backend && python manage.py collectstatic --noinput",
  "cd backend && python manage.py migrate"
]

[start]
cmd = "cd backend && gunicorn recruitment_system.wsgi --bind 0.0.0.0:$PORT"
